BackendBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BackendBundle\Repository\CommentRepository
    indexes:
        fk_comment_video:
            columns:
                - video_id
        fk_comment_user:
            columns:
                - user_id        
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        videoId:
            type: integer
            column: video_id
        userId:
            type: integer
            column: user_id
        body:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        video:
            targetEntity: Video
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                video_id:
                    referenceColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referenceColumnName: id
            orphanRemoval: false               
    lifecycleCallbacks: {  }
