BackendBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BackendBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
            nullable: true
        image:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
