BackendBundle\Entity\Video:
    type: entity
    table: null
    repositoryClass: BackendBundle\Repository\VideoRepository
    indexes:
        fk_video_user:
            columns:
                - user_id        
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: 255
        image:
            type: string
            length: 255
            nullable: true
        videoPath:
            type: string
            length: 255
            column: video_path
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at        
    manyToOne:
        user:
            targetEntity: User
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referenceColumnName: id
            orphanRemoval: false         
    lifecycleCallbacks: {  }
